feat: backfilling faucet and offchain backfilling of data
fermionprotocol/contracts pull request #342
Opened 2024-12-19 10:16 UTC by 0xlucian

Close #303

2025-03-24 11:44 UTC, zajck requested changes

2025-03-24 11:44 UTC, zajck commented on scripts/upgrade-hooks/subgraph_config.json
> +  "testing": {
```suggestion
  "test": {
```
Just to be in line with how we store it in the addresses.

2025-03-24 11:44 UTC, zajck commented on scripts/upgrade-hooks/1.1.0.ts
> +  const addressData = JSON.parse(addressFile);
Not a correct path in `addressFile`, since the addresses filename also includes `network`.

Also, I suggest using 
```const addressData = await readContracts(env)```
Where `readContracts` is from `libraries/utils` which does the job and also handles some special cases for filepaths.

2025-03-24 11:44 UTC, zajck commented on scripts/upgrade-hooks/1.1.0.ts
> +async function fetchGraphQLData(client: any): Promise<Offer[]> {
Maybe a bit misleading name if we have `fetchFNFTRangeData` for the other case, we could have `fetchOfferData` or sth similar here.

2025-03-24 11:44 UTC, zajck commented on scripts/upgrade-hooks/1.1.0.ts
> +  const facilitatorFeeAmount = remainder > 0n ? (remainder * facilitatorFeePercentBps) / HUNDRED_PERCENT_BPS : 0n;
```suggestion
  const facilitatorFeeAmount =  (remainder * facilitatorFeePercentBps) / HUNDRED_PERCENT_BPS;
```
Should be the same without the ternary operator. If `remainder` is negative, something went wrong before that.

2025-03-24 11:44 UTC, zajck commented on scripts/upgrade-hooks/1.1.0.ts
> +      const price = token.priceLog?.amount ? BigInt(token.priceLog.amount) : 0n;
Need a confirmation - is this the full price, or the price without the boson fee? I'm not sure what is stored in the subgraph. If it's already stored without fees, then `calculateFees` calculation are not correct.  
Please document it in either case.

2025-03-24 11:44 UTC, zajck commented on scripts/upgrade-hooks/1.1.0.ts
> +  const backFillOfferCalldata = backfillingFacet.interface.encodeFunctionData("backFillOfferData", [offerDataList]);
Maybe it's worth doing an estimate how much data can we fill in in a single tx before running into gasLimit. If there is too much data, we might need to split it into multiple calls. 

But that's not a scope of this PR, since I don't really expect a problem (at least not on mainnets).

2025-03-24 11:44 UTC, zajck commented on test/upgrade/1.0.0-1.1.0.ts
> +          verifierFee: 10,
Maybe pick a different number that was the original `verifierFee`, just to make sure the new value is stored.

Or alternatively, after you set the fees to 0 with `setStorageAt` make another check with `getStorageAt` to see they really are 0.

2025-03-24 11:44 UTC, zajck commented on test/upgrade/1.0.0-1.1.0.ts
> +
Also check the value of `tokenLookup.itemPrice` which should change, too.

2025-03-24 14:36 UTC, levalleux-ludo commented on scripts/upgrade-hooks/1.1.0.ts
> +      const price = token.priceLog?.amount ? BigInt(token.priceLog.amount) : 0n;
At the moment (until [this issue](https://github.com/fermionprotocol/core-components/issues/129) will be dealt with), the `priceLog.amount` in subgraph data model is defined from the the `amount` property of the `FundsEncumbered` event emitted by Boson protocol in the same transaction when the `VerificationInitiated` event is raised by Fermion).
I think it means the `actualPrice = balanceAfter - balanceBefore` as set by the price discovery client (https://github.com/bosonprotocol/boson-protocol-contracts/blob/f099648a49045c8bad1a1bdb8e2c4ffcf67b69da/contracts/protocol/clients/priceDiscovery/BosonPriceDiscovery.sol#L192)

2025-03-24 14:38 UTC, levalleux-ludo commented on scripts/upgrade-hooks/subgraph_config.json
> +  "testing": {
in core-components, we've always called our environments testing, staging and production
https://github.com/bosonprotocol/core-components/blob/ad1584da1f59383a7ce3581abbf8e6a663371474/packages/common/src/types/configs.ts#L15

2025-03-24 14:40 UTC, zajck commented on scripts/upgrade-hooks/subgraph_config.json
> +  "testing": {
Or we can change everything to "testing" here (and in Boson), I don't mind.

I just pointed it out since I noticed that the reading subgraph config is not compatibile with reading the addresses. Or we can introduce some remappings, but that it personally find ugly (I think I did sth similar somewhere because Boson uses "mainnet" and fermion uses "ethereum").

2025-03-24 14:51 UTC, zajck commented on scripts/upgrade-hooks/1.1.0.ts
> +      const price = token.priceLog?.amount ? BigInt(token.priceLog.amount) : 0n;
Ok, so this is the full price (already stripped from any external fees, such as opensea fee), which is ok.

This means that `calculateFees` in `1.0.0.ts` works ok and it looks to me, we are filling in the correct values to backfilling faucet.

I think that resolving https://github.com/fermionprotocol/core-components/issues/129 would actually make the data inconsistent if `ItemPriceObserved` would be used directly for `priceLog.amount`. Since `ItemPriceObserved` in `1.0.1` does not include the BPFee, while `1.1.0` will again contain the price with BPFee. We need to be careful how to handle this.

2025-03-24 14:55 UTC, levalleux-ludo commented on scripts/upgrade-hooks/subgraph_config.json
> +  "testing": {
https://github.com/bosonprotocol/core-components/blob/ad1584da1f59383a7ce3581abbf8e6a663371474/packages/common/src/types/configs.ts#L37

2025-03-24 14:56 UTC, levalleux-ludo commented on scripts/upgrade-hooks/subgraph_config.json
> +  "testing": {
^^ compared to the protocol deployment addresses files, we don't use any label for the chains, only chainId (less confusion possible)

2025-03-24 14:58 UTC, levalleux-ludo commented on scripts/upgrade-hooks/subgraph_config.json
> +  "testing": {
FYI, I've added a reverse mapping data config in this script, but I agree this is a bit ugly:

2025-03-25 10:11 UTC, zajck approved these changes
LGTM

2025-03-25 13:56 UTC, levalleux-ludo commented on contracts/protocol/facets/backfill/BackfillingV1_1_0.sol
> +    function backFillTokenFees(FeeData[] calldata feeDataList) external {
OK. Good to know. Thanks for the explanation

2025-03-25 14:01 UTC, levalleux-ludo commented on test/upgrade/1.0.0-1.1.0.ts
> +async function executeBackfillingDiamondCut(
An example:
- in preUpgrade:
  `await diamondCutFacet.diamondCut([], initializationFacetAddress, backfillingCalldata);`
- in test:
  `await diamondCutFacet.diamondCut([], initializationFacetImplementationAddress, initCalldata);`

^^ it makes me think `initializationFacetAddress == initializationFacetImplementationAddress` and `backfillingCalldata == initCalldata`. But, if so, why not use the same variable name. Or better, implement 1 function and call it from preUpgrade and from the test code

2025-03-25 14:03 UTC, levalleux-ludo commented on test/upgrade/1.0.0-1.1.0.ts
> +async function executeBackfillingDiamondCut(
Just another example: 
- in preUpgrade:
  ```
const backfillingCalldata = abiCoder.encode(
    ["bytes32", "address[]", "bytes[]", "bytes4[]", "bytes4[]"],
    [version, addresses, calldata, interfacesToAdd, interfacesToRemove],
  );
```
- in test:
 ```
 const initCalldata = initializationFacet.interface.encodeFunctionData("initialize", [
    version,
    [backfillingFacetAddress, backfillingFacetAddress],
    [offerBackfillCalldata, tokenBackfillCalldata],
    [],
    [],
  ]);
```

2025-03-25 14:04 UTC, levalleux-ludo commented on test/upgrade/1.0.0-1.1.0.ts
> +async function executeBackfillingDiamondCut(
I think the best would be to implement one function and call it from preUpgrade and from the test code

2025-03-26 07:11 UTC, zajck commented on test/upgrade/1.0.0-1.1.0.ts
> +async function executeBackfillingDiamondCut(
My 2c on this - #343 will do exactly what you suggest @levalleux-ludo and there we'll also test that the upgrade is ok in all aspects.

Here in the unit tests of this PRs we test only that the smart contracts are doing what they are supposed to, so to me it's ok if the setup here is not using the preUpgrade script.

2025-03-26 08:45 UTC, zajck approved these changes

2025-03-26 10:17 UTC, levalleux-ludo submitted a review, later dismissed

2025-03-26 10:18 UTC, zajck approved these changes

2025-03-26 10:28 UTC, zajck approved these changes

2025-03-26 10:36 UTC, levalleux-ludo approved these changes

2025-03-26 10:37 UTC, merged